/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Customer;
import Utility.DatabaseConnector;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yashu
 */
public class FormJPanel extends javax.swing.JPanel {

    ImageIcon profilePicture;
    JPanel bottomjPanel;
    /**
     * Creates new form FormJPanel
     * @param bottomjPanel
     */
    public FormJPanel(JPanel bottomjPanel) {
        this.bottomjPanel = bottomjPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelFullname = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFullName = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonOthers = new javax.swing.JRadioButton();
        jTextAge = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        jLabelAppointtype = new javax.swing.JLabel();
        appointTypejComboBox = new javax.swing.JComboBox<>();
        imgJLabel = new javax.swing.JLabel();
        jLabelCarmake = new javax.swing.JLabel();
        jTextPhone = new javax.swing.JTextField();
        jLabelPhone = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextCarmake = new javax.swing.JTextField();
        jLabelCarmodel = new javax.swing.JLabel();
        jTextCarmodel = new javax.swing.JTextField();
        jLabelYearmake = new javax.swing.JLabel();
        jLabelAppointdate = new javax.swing.JLabel();
        jLabelCarphoto = new javax.swing.JLabel();
        jButtonPhoto = new javax.swing.JButton();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jButtonSubmit = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabelFullname.setText("FULL NAME:");

        jLabelTitle.setText("Quotation Form");

        jTextFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFullNameActionPerformed(evt);
            }
        });

        jLabelGender.setText("GENDER:");

        buttonGroupGender.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.setActionCommand("male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.setActionCommand("female");
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonOthers);
        jRadioButtonOthers.setText("Others");
        jRadioButtonOthers.setActionCommand("others");
        jRadioButtonOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOthersActionPerformed(evt);
            }
        });

        jLabelAge.setText("AGE:");

        jLabelAppointtype.setText("APPOINTMENT TYPE:");

        appointTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appointment", "virtual", "walk-in" }));
        appointTypejComboBox.setSelectedIndex(-1);
        appointTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointTypejComboBoxActionPerformed(evt);
            }
        });

        jLabelCarmake.setText("CAR MAKE:");

        jLabelPhone.setText("PHONE NO.:");

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jLabelEmail.setText("EMAIL:");

        jLabelCarmodel.setText("CAR MODEL:");

        jLabelYearmake.setText("YEAR OF MAKE:");

        jLabelAppointdate.setText("APPOINTMENT DATE:");

        jLabelCarphoto.setText("UPLOAD CAR PHOTO:");

        jButtonPhoto.setText("Upload Photo");
        jButtonPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabelTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelGender)
                            .addComponent(jLabelFullname)
                            .addComponent(jLabelAge)
                            .addComponent(jLabelPhone)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelCarmake)
                            .addComponent(jLabelCarmodel)
                            .addComponent(jLabelYearmake)
                            .addComponent(jLabelCarphoto)
                            .addComponent(jLabelAppointtype)
                            .addComponent(jLabelAppointdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPhoto)
                                    .addComponent(appointTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(imgJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonMale)
                                    .addComponent(jTextFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonFemale)
                                    .addComponent(jRadioButtonOthers)
                                    .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextCarmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextCarmake, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFullname)
                    .addComponent(jTextFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGender)
                    .addComponent(jRadioButtonMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFemale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOthers)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAge)
                    .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone)
                    .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarmake)
                    .addComponent(jTextCarmake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarmodel)
                    .addComponent(jTextCarmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(imgJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabelAppointdate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelYearmake))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCarphoto)
                            .addComponent(jButtonPhoto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAppointtype, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSubmit)
                        .addGap(316, 316, 316))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSubmit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFullNameActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jRadioButtonOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOthersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOthersActionPerformed

    private void appointTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointTypejComboBoxActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
    
    try {
            String fullname = this.jTextFullName.getText();
            String age = this.jTextAge.getText();
            String phone = this.jTextPhone.getText();
            String email = this.jTextEmail.getText();
            String carmake = this.jTextCarmake.getText();
            String carmodel = this.jTextCarmodel.getText();
            Date appointdate = this.jDateChooser.getDate();
            int makeyear = this.jYearChooser.getYear();
            String appointType = this.appointTypejComboBox.getSelectedItem().toString();
            if (fullname.isEmpty() || age.isEmpty() || phone.isEmpty() || 
            email.isEmpty() || carmake.isEmpty() || carmodel.isEmpty() || 
            appointType.isEmpty() || appointdate == null) {
            JOptionPane.showMessageDialog(
                this, 
                "All fields are required.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
            if (!age.matches("\\d+")) { 
    JOptionPane.showMessageDialog(
        this,
        "Age must be a numeric value.",
        "Validation Error",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}

int ageValue = Integer.parseInt(age); // Safely parse after validation

if (ageValue <= 0 || ageValue > 120) { 
    JOptionPane.showMessageDialog(
        this,
        "Age must be between 1 and 120.",
        "Validation Error",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}
            if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
                JOptionPane.showMessageDialog(
        this, 
        "Invalid email format.", 
        "Validation Error", 
        JOptionPane.ERROR_MESSAGE
    );
    return;
}
            if (!phone.matches("\\d{10}")) {
    JOptionPane.showMessageDialog(
        this, 
        "Phone number must be 10 digits.", 
        "Validation Error", 
        JOptionPane.ERROR_MESSAGE
    );
    return;
}
        if (this.buttonGroupGender.getSelection() == null) {
            JOptionPane.showMessageDialog(
                this, 
                "Please select a gender.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        String gender = this.buttonGroupGender.getSelection().getActionCommand();

        // Profile Picture Validation
        // Construct display message
        String displayMessage = "Full name: " + fullname + " Gender: " + gender + " Age: " + age + " Phone no.: " + phone + " Email: " + email + " Car Make: " + carmake + " Car Model: " + carmodel + " Year of Make: " + makeyear + " Appointment Date: " + appointdate + " Appointment Type: " + appointType;

        // Print inputs for debugging
        System.out.println(fullname);
        System.out.println(gender);
        System.out.println(age);
       System.out.println(phone);
       System.out.println(email);
       System.out.println(carmake);
       System.out.println(carmodel);
       System.out.println(makeyear);
       System.out.println(appointType);
       System.out.println(appointdate);


        // Show message dialog
        JOptionPane.showMessageDialog(this, displayMessage, "Success", JOptionPane.INFORMATION_MESSAGE, profilePicture);
            System.out.println(this.jTextFullName.getText());
            System.out.println(this.buttonGroupGender.getSelection().getActionCommand());
            System.out.println(this.jTextAge.getText());
            System.out.println(this.jTextPhone.getText());
            System.out.println(this.jTextEmail.getText());
            System.out.println(this.jTextCarmake.getText());
            System.out.println(this.jTextCarmodel.getText());
            System.out.println(this.jYearChooser.getYear());
            System.out.println(this.appointTypejComboBox.getSelectedItem().toString());
            System.out.println((Date) this.jDateChooser.getDate());
            

        
            JOptionPane.showMessageDialog(this, displayMessage, "success", HEIGHT, profilePicture);
            Customer c1 = new Customer();
            c1.setFullname(fullname);
            c1.setGender(gender);
            c1.setAge(age);
            c1.setPhone(phone);
            c1.setEmail(email);
            c1.setCarmake(carmake);
            c1.setCarmodel(carmodel);
            c1.setMakeyear(makeyear);
            c1.setAppointType(appointType);
            c1.setAppointdate(new java.sql.Date(appointdate.getTime())); // Ensure correct type for database
             DatabaseConnector.addCustomer(c1);
            System.out.print("the customer is added");
        
           

         ViewJPanel newViewJPanel = new ViewJPanel(c1);
        bottomjPanel.add(newViewJPanel, "ViewJPanel");
        CardLayout layout = (CardLayout) this.bottomjPanel.getLayout();
        layout.show(bottomjPanel, "ViewJPanel");

        // Revalidate and repaint the container
        bottomjPanel.revalidate();
        bottomjPanel.repaint();

        System.out.println("Switched to ViewJPanel successfully.");
    
        
    } catch (Exception ex) {
        Logger.getLogger(FormJPanel.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    

    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhotoActionPerformed
        JFileChooser file = new JFileChooser();
        if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage img = ImageIO.read(file.getSelectedFile());
                Image edited_image = img.getScaledInstance(60, 80,Image.SCALE_SMOOTH);
                if (edited_image != null) {
                    this.imgJLabel.setText(file.getSelectedFile().getAbsolutePath());
                    this.imgJLabel.setIcon(new ImageIcon(edited_image));
                    this.profilePicture = (new ImageIcon(edited_image));
                    //this.userInfo.setPic(new ImageIcon(edited_image));
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please upload image correctly", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPhotoActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> appointTypejComboBox;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JLabel imgJLabel;
    private javax.swing.JButton jButtonPhoto;
    private javax.swing.JButton jButtonSubmit;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelAppointdate;
    private javax.swing.JLabel jLabelAppointtype;
    private javax.swing.JLabel jLabelCarmake;
    private javax.swing.JLabel jLabelCarmodel;
    private javax.swing.JLabel jLabelCarphoto;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFullname;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelYearmake;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOthers;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextCarmake;
    private javax.swing.JTextField jTextCarmodel;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFullName;
    private javax.swing.JTextField jTextPhone;
    private com.toedter.calendar.JYearChooser jYearChooser;
    // End of variables declaration//GEN-END:variables
}
