/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Patient;
import Utility.DatabaseConnector;
import java.util.ArrayList;

import javax.swing.ImageIcon;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yashu
 */
public final class ViewJPanel extends javax.swing.JPanel {
        ArrayList <Patient> patients;
        Patient selectedPatient;
        ImageIcon profilePicture;
    Patient p1;
    /**
     * Creates new form FormJPanel
     */
    public ViewJPanel() {
        initComponents();
        populateTable();
        disableAll();
    }
    
    public ViewJPanel(Patient p1){
        this.p1 = p1;
        initComponents();
        populateTable();
        populateData();
        disableAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelFirstname = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFirstName = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonOthers = new javax.swing.JRadioButton();
        jTextAge = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        jLabelpatienttype = new javax.swing.JLabel();
        patientTypejComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jdeleteButton = new javax.swing.JButton();
        jeditButton = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabelFirstname.setText("FIRST NAME:");

        jLabelTitle.setText("Patient Registration Form");

        jTextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFirstNameActionPerformed(evt);
            }
        });

        jLabelGender.setText("GENDER:");

        buttonGroupGender.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.setActionCommand("male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.setActionCommand("female");
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });

        buttonGroupGender.add(jRadioButtonOthers);
        jRadioButtonOthers.setText("Others");
        jRadioButtonOthers.setActionCommand("others");
        jRadioButtonOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOthersActionPerformed(evt);
            }
        });

        jLabelAge.setText("AGE:");

        jLabelpatienttype.setText("PATIENT TYPE:");

        patientTypejComboBox.setEditable(true);
        patientTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appointment", "virtual", "walk-in" }));
        patientTypejComboBox.setSelectedIndex(-1);
        patientTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTypejComboBoxActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "firstname", "age", "gender", "patientType"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setDropMode(javax.swing.DropMode.ON);
        jScrollPane1.setViewportView(jTable1);

        jdeleteButton.setText("delete row");
        jdeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteButtonActionPerformed(evt);
            }
        });

        jeditButton.setText("Edit row");
        jeditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditButtonActionPerformed(evt);
            }
        });

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabelTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelGender)
                                    .addComponent(jLabelAge)
                                    .addComponent(jLabelpatienttype)
                                    .addComponent(jLabelFirstname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonMale)
                                    .addComponent(jRadioButtonFemale)
                                    .addComponent(jRadioButtonOthers)
                                    .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jeditButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSubmit)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstname)
                            .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGender)
                            .addComponent(jRadioButtonMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOthers)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAge)
                            .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelpatienttype, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdeleteButton)
                            .addComponent(jButtonSubmit))
                        .addGap(28, 28, 28)
                        .addComponent(jeditButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFirstNameActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jRadioButtonOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOthersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOthersActionPerformed

    private void patientTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTypejComboBoxActionPerformed

    private void jdeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteButtonActionPerformed
       int selectedRowIndex = this.jTable1.getSelectedRow();
    
    if (selectedRowIndex == -1) {
        System.out.println("No row selected."); // Check if a row is selected
        return; // Exit if no row is selected
    }
    
    this.selectedPatient = this.patients.get(selectedRowIndex);
    
    try {
        DatabaseConnector.deletePatient(selectedPatient); // Delete patient
        System.out.println("Patient deleted successfully");
        populateTable(); // Refresh the table data
        this.jTable1.repaint(); // Force table UI refresh
    } catch (Exception e) {
        System.out.println("Unable to delete the patient");
        e.printStackTrace(); // Print the full error stack trace
    }
 
    }//GEN-LAST:event_jdeleteButtonActionPerformed

    private void jeditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditButtonActionPerformed
            int selectedRowIndex = this.jTable1.getSelectedRow();
            enableAll();
            this.selectedPatient = this.patients.get(selectedRowIndex);
            populateData();
    }//GEN-LAST:event_jeditButtonActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
            Patient updatedPatient = new Patient();
            updatedPatient.setFirstname (this.jTextFirstName.getText());
            updatedPatient.setGender(this.buttonGroupGender.getSelection().getActionCommand());
            updatedPatient.setAge(this.jTextAge.getText());
            updatedPatient.setPatientType(this.patientTypejComboBox.getSelectedItem().toString());
            DatabaseConnector.updatePatient(selectedPatient, updatedPatient);
            populateTable();
    }//GEN-LAST:event_jButtonSubmitActionPerformed
    public void populateTable(){
        this.patients = DatabaseConnector.getPatients();
        DefaultTableModel model = (DefaultTableModel)  this.jTable1.getModel();
        model.setColumnIdentifiers(new String[] {"ID", "First Name", "Age", "Gender", "Patient Type"});

        model.setRowCount(0);
        for (Patient p1: patients){
            Object [] row = new Object[5];
            row[0] = p1.getId();
            row[1] = p1.getFirstname();
            row[2] = p1.getAge();
            row[3] = p1.getGender();
            row[4] = p1.getPatientType();
            model.addRow(row);

        }
    }
    
    
    public void populateData(){
        this.jTextFirstName.setText(p1.getFirstname());
        this.jTextAge.setText(p1.getAge());
        this.patientTypejComboBox.setSelectedItem(p1.getPatientType());
        String gender = p1.getGender();
        if(gender.equals("male")){
        this.buttonGroupGender.setSelected(this.jRadioButtonMale.getModel(), true);
    }else if(gender.equals("female")){
        this.buttonGroupGender.setSelected(this.jRadioButtonFemale.getModel(), true);
    } else {
        this.buttonGroupGender.setSelected(this.jRadioButtonOthers.getModel(), true);
    }
    }
        public void enableAll(){
        this.jRadioButtonFemale.setEnabled(true);
        this.jRadioButtonMale.setEnabled(true);
        this.jRadioButtonOthers.setEnabled(true);
        this.patientTypejComboBox.setEnabled(true);
        this.jTextFirstName.setEnabled(true);
        this.jTextAge.setEnabled(true);
}
        public void disableAll(){

        this.jRadioButtonFemale.setEnabled(false);
        this.jRadioButtonMale.setEnabled(false);
        this.jRadioButtonOthers.setEnabled(false);
        this.patientTypejComboBox.setEnabled(false);
        this.jTextFirstName.setEnabled(false);
        this.jTextAge.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelFirstname;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelpatienttype;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOthers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JButton jdeleteButton;
    private javax.swing.JButton jeditButton;
    private javax.swing.JComboBox<String> patientTypejComboBox;
    // End of variables declaration//GEN-END:variables
}
